"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EventEnvelope(_message.Message):
    """Lineage-critical envelope for ALL platform events (Spec FR-023, §47).
    event_id is the idempotency key for consumers.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EVENT_ID_FIELD_NUMBER: _builtins.int
    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    EVENT_VERSION_FIELD_NUMBER: _builtins.int
    INVESTIGATION_ID_FIELD_NUMBER: _builtins.int
    CORRELATION_ID_FIELD_NUMBER: _builtins.int
    CAUSATION_ID_FIELD_NUMBER: _builtins.int
    PRODUCER_FIELD_NUMBER: _builtins.int
    PRODUCER_VERSION_FIELD_NUMBER: _builtins.int
    PRODUCED_AT_FIELD_NUMBER: _builtins.int
    OBSERVATION_ID_FIELD_NUMBER: _builtins.int
    ENTITY_ID_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    TENANT_ID_FIELD_NUMBER: _builtins.int
    SOURCE_ID_FIELD_NUMBER: _builtins.int
    WORK_ID_FIELD_NUMBER: _builtins.int
    REGION_ID_FIELD_NUMBER: _builtins.int
    event_id: _builtins.str
    """uuid; consumer idempotency key"""
    event_type: _builtins.str
    """e.g. "observation.created" """
    event_version: _builtins.str
    """per-type payload version"""
    investigation_id: _builtins.str
    correlation_id: _builtins.str
    """lineage: root intent correlation"""
    causation_id: _builtins.str
    """lineage: direct cause event"""
    producer: _builtins.str
    """e.g. "acquisition.worker-http" """
    producer_version: _builtins.str
    produced_at: _builtins.str
    """RFC3339"""
    observation_id: _builtins.str
    entity_id: _builtins.str
    payload: _builtins.bytes
    """typed per event_type, registry-validated"""
    tenant_id: _builtins.str
    """v2 / Global Collection Fabric additions (T103): tenant isolation at the
    envelope level and routing/trace bookkeeping. tenant_id MUST be set on
    every envelope (produced at the authorized boundary).
    """
    source_id: _builtins.str
    work_id: _builtins.str
    region_id: _builtins.str
    def __init__(
        self,
        *,
        event_id: _builtins.str = ...,
        event_type: _builtins.str = ...,
        event_version: _builtins.str = ...,
        investigation_id: _builtins.str = ...,
        correlation_id: _builtins.str = ...,
        causation_id: _builtins.str = ...,
        producer: _builtins.str = ...,
        producer_version: _builtins.str = ...,
        produced_at: _builtins.str = ...,
        observation_id: _builtins.str = ...,
        entity_id: _builtins.str = ...,
        payload: _builtins.bytes = ...,
        tenant_id: _builtins.str = ...,
        source_id: _builtins.str = ...,
        work_id: _builtins.str = ...,
        region_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["causation_id", b"causation_id", "correlation_id", b"correlation_id", "entity_id", b"entity_id", "event_id", b"event_id", "event_type", b"event_type", "event_version", b"event_version", "investigation_id", b"investigation_id", "observation_id", b"observation_id", "payload", b"payload", "produced_at", b"produced_at", "producer", b"producer", "producer_version", b"producer_version", "region_id", b"region_id", "source_id", b"source_id", "tenant_id", b"tenant_id", "work_id", b"work_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EventEnvelope: _TypeAlias = EventEnvelope  # noqa: Y015
